version: '3.3'

services:
  vscode:
    build:
      context: ./vscode
      dockerfile: Dockerfile
      args:
        VARIANT: "11"
        INSTALL_MAVEN: "false"
        INSTALL_GRADLE: "false"
        INSTALL_NODE: "true"
        NODE_VERSION: "lts/*"

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace:cached
      # Forwards the local Docker socket to the container.
      #- /var/run/docker.sock:/var/run/docker-host.sock

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  structurizr:
    image: tomcat:9.0.38-jdk11-openjdk
    restart: always
    ports:
      - "1315:8080"
    volumes:
      - ./structurizr/war/structurizr-onpremises.war:/usr/local/tomcat/webapps/ROOT.war
      - ./structurizr/data:/usr/local/structurizr